// Constants used for Note Reducer and Note Actions
export const noteConstants = {
  RECEIVING_NOTES: 'RECEIVING_NOTES',
  RECEIVE_NOTES: 'RECEIVE_NOTES',

  ADD_NOTE: 'ADD_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',

  SET_CURRENT_NOTE: 'SET_CURRENT_NOTE',

  ADD_COLLABORATOR: 'ADD_COLLABORATOR',
  REMOVE_COLLABORATOR: 'REMOVE_COLLABORATOR',

  SWITCH_TYPE: 'SWITCH_TYPE',
  SWITCH_BODY: 'SWITCH_BODY',

  ADD_ITEM: 'ADD_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CHECK_ITEM: 'CHECK_ITEM',

  SET_SEARCH_TERM: 'SET_SEARCH_TERM'
}
