export const noteConstants = {
  RECEIVING_NOTES: 'RECEIVING_NOTES',
  RECEIVE_NOTES: 'RECEIVE_NOTES',
  ADD_NOTE: 'ADD_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  SET_CURRENT_NOTE: 'SET_CURRENT_NOTE',

  ADD_COLLABORATOR: 'ADD_COLLABORATOR',
  REMOVE_COLLABORATOR: 'REMOVE_COLLABORATOR',
  UPDATE_COLLABORATORS: 'UPDATE_COLLABORATORS'
}
